name: Lint Markdown

on: push

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run mdl
        uses: actionshub/markdownlint@main
